apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eu
        echo "Cleaning workspace..."
        rm -rf $(workspaces.source.path)/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  steps:
    - name: npminstall
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Node version:"
        node -v
        npm -v

        echo "Installing dependencies..."
        npm install

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: runtests
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Running Jasmine tests..."
        npx jasmine

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-app-pipeline
spec:
  workspaces:
    - name: shared-workspace

  tasks:
    - name: cleanup-task
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: npm-install
      taskRef:
        name: npm
      runAfter:
        - cleanup-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: run-tests
      taskRef:
        name: jasmine
      runAfter:
        - npm-install
      workspaces:
        - name: source
          workspace: shared-workspace

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-app-pipeline-run
spec:
  pipelineRef:
    name: tax-app-pipeline
  workspaces:
    - name: shared-workspace
      emptyDir: {}
